add follower feature

diff --git a/socialapp/cli/socialapp-cli b/socialapp/cli/socialapp-cli
--- a/socialapp/cli/socialapp-cli
+++ b/socialapp/cli/socialapp-cli
@@ -100,8 +100,13 @@ operation_parameters_minimum_occurrences["getComment:::id"]=1
 operation_parameters_minimum_occurrences["getUserComments:::username"]=1
 operation_parameters_minimum_occurrences["createUser:::User"]=1
 operation_parameters_minimum_occurrences["deleteUser:::username"]=1
+operation_parameters_minimum_occurrences["followUser:::followedUsername"]=1
+operation_parameters_minimum_occurrences["followUser:::followerUsername"]=1
 operation_parameters_minimum_occurrences["getUserByUsername:::username"]=1
 operation_parameters_minimum_occurrences["getUserComments:::username"]=1
+operation_parameters_minimum_occurrences["getUserFollowers:::username"]=1
+operation_parameters_minimum_occurrences["unfollowUser:::followedUsername"]=1
+operation_parameters_minimum_occurrences["unfollowUser:::followerUsername"]=1
 operation_parameters_minimum_occurrences["updateUser:::username"]=1
 operation_parameters_minimum_occurrences["updateUser:::User"]=0
 
@@ -117,8 +122,13 @@ operation_parameters_maximum_occurrences["getComment:::id"]=0
 operation_parameters_maximum_occurrences["getUserComments:::username"]=0
 operation_parameters_maximum_occurrences["createUser:::User"]=0
 operation_parameters_maximum_occurrences["deleteUser:::username"]=0
+operation_parameters_maximum_occurrences["followUser:::followedUsername"]=0
+operation_parameters_maximum_occurrences["followUser:::followerUsername"]=0
 operation_parameters_maximum_occurrences["getUserByUsername:::username"]=0
 operation_parameters_maximum_occurrences["getUserComments:::username"]=0
+operation_parameters_maximum_occurrences["getUserFollowers:::username"]=0
+operation_parameters_maximum_occurrences["unfollowUser:::followedUsername"]=0
+operation_parameters_maximum_occurrences["unfollowUser:::followerUsername"]=0
 operation_parameters_maximum_occurrences["updateUser:::username"]=0
 operation_parameters_maximum_occurrences["updateUser:::User"]=0
 
@@ -131,8 +141,13 @@ operation_parameters_collection_type["getComment:::id"]=""
 operation_parameters_collection_type["getUserComments:::username"]=""
 operation_parameters_collection_type["createUser:::User"]=""
 operation_parameters_collection_type["deleteUser:::username"]=""
+operation_parameters_collection_type["followUser:::followedUsername"]=""
+operation_parameters_collection_type["followUser:::followerUsername"]=""
 operation_parameters_collection_type["getUserByUsername:::username"]=""
 operation_parameters_collection_type["getUserComments:::username"]=""
+operation_parameters_collection_type["getUserFollowers:::username"]=""
+operation_parameters_collection_type["unfollowUser:::followedUsername"]=""
+operation_parameters_collection_type["unfollowUser:::followerUsername"]=""
 operation_parameters_collection_type["updateUser:::username"]=""
 operation_parameters_collection_type["updateUser:::User"]=""
 
@@ -536,9 +551,12 @@ echo "  $ops" | column -t -s ';'
 read -r -d '' ops <<EOF
   ${CYAN}createUser${OFF};Create a new user (AUTH) (AUTH)
   ${CYAN}deleteUser${OFF};Deletes a particular user (AUTH) (AUTH)
+  ${CYAN}followUser${OFF};Add a user as a follower (AUTH) (AUTH)
   ${CYAN}getUserByUsername${OFF};Get a particular user by username (AUTH) (AUTH)
   ${CYAN}getUserComments${OFF};Gets all comments for a user (AUTH) (AUTH)
+  ${CYAN}getUserFollowers${OFF};Get all followers for a user (AUTH) (AUTH)
   ${CYAN}listUsers${OFF};Returns all the users (AUTH) (AUTH)
+  ${CYAN}unfollowUser${OFF};Remove a user as a follower (AUTH) (AUTH)
   ${CYAN}updateUser${OFF};Update a user (AUTH) (AUTH)
 EOF
 echo "  $ops" | column -t -s ';'
@@ -689,6 +707,25 @@ print_deleteUser_help() {
 }
 ##############################################################################
 #
+# Print help for followUser operation
+#
+##############################################################################
+print_followUser_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}followUser - Add a user as a follower${OFF}${BLUE}(AUTH - BASIC)${OFF}${BLUE}(AUTH - BASIC)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}followedUsername${OFF} ${BLUE}[string]${OFF} ${RED}(required)${OFF} ${CYAN}(default: null)${OFF} - username of the user ${YELLOW}Specify as: followedUsername=value${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e "  * ${GREEN}followerUsername${OFF} ${BLUE}[string]${OFF} ${RED}(required)${OFF} ${CYAN}(default: null)${OFF} - username of the follower ${YELLOW}Specify as: followerUsername=value${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=200
+    echo -e "${result_color_table[${code:0:1}]}  200;User was followed successfully${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=0
+    echo -e "${result_color_table[${code:0:1}]}  0;Unexpected error${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
 # Print help for getUserByUsername operation
 #
 ##############################################################################
@@ -727,6 +764,24 @@ print_getUserComments_help() {
 }
 ##############################################################################
 #
+# Print help for getUserFollowers operation
+#
+##############################################################################
+print_getUserFollowers_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}getUserFollowers - Get all followers for a user${OFF}${BLUE}(AUTH - BASIC)${OFF}${BLUE}(AUTH - BASIC)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}username${OFF} ${BLUE}[string]${OFF} ${RED}(required)${OFF} ${CYAN}(default: null)${OFF} - username of the user ${YELLOW}Specify as: username=value${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=200
+    echo -e "${result_color_table[${code:0:1}]}  200;User followers${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=0
+    echo -e "${result_color_table[${code:0:1}]}  0;Unexpected error${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
 # Print help for listUsers operation
 #
 ##############################################################################
@@ -738,6 +793,25 @@ print_listUsers_help() {
     echo -e "${BOLD}${WHITE}Responses${OFF}"
     code=200
     echo -e "${result_color_table[${code:0:1}]}  200;Details about a user by ID${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=0
+    echo -e "${result_color_table[${code:0:1}]}  0;Unexpected error${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
+# Print help for unfollowUser operation
+#
+##############################################################################
+print_unfollowUser_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}unfollowUser - Remove a user as a follower${OFF}${BLUE}(AUTH - BASIC)${OFF}${BLUE}(AUTH - BASIC)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}followedUsername${OFF} ${BLUE}[string]${OFF} ${RED}(required)${OFF} ${CYAN}(default: null)${OFF} - username of the user ${YELLOW}Specify as: followedUsername=value${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e "  * ${GREEN}followerUsername${OFF} ${BLUE}[string]${OFF} ${RED}(required)${OFF} ${CYAN}(default: null)${OFF} - username of the follower ${YELLOW}Specify as: followerUsername=value${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=200
+    echo -e "${result_color_table[${code:0:1}]}  200;User was unfollowed successfully${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
     code=0
     echo -e "${result_color_table[${code:0:1}]}  0;Unexpected error${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
 }
@@ -1029,6 +1103,42 @@ call_deleteUser() {
 
 ##############################################################################
 #
+# Call followUser operation
+#
+##############################################################################
+call_followUser() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=(followedUsername followerUsername)
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(    )
+    local path
+
+    if ! path=$(build_request_path "/users/{followedUsername}/followers/{followerUsername}" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="POST"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    if [[ "$print_curl" = true ]]; then
+        echo "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    else
+        eval "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    fi
+}
+
+##############################################################################
+#
 # Call getUserByUsername operation
 #
 ##############################################################################
@@ -1101,6 +1211,42 @@ call_getUserComments() {
 
 ##############################################################################
 #
+# Call getUserFollowers operation
+#
+##############################################################################
+call_getUserFollowers() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=(username)
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(    )
+    local path
+
+    if ! path=$(build_request_path "/users/{username}/followers" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="GET"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    if [[ "$print_curl" = true ]]; then
+        echo "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    else
+        eval "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    fi
+}
+
+##############################################################################
+#
 # Call listUsers operation
 #
 ##############################################################################
@@ -1118,6 +1264,42 @@ call_listUsers() {
         exit 1
     fi
     local method="GET"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    if [[ "$print_curl" = true ]]; then
+        echo "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    else
+        eval "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    fi
+}
+
+##############################################################################
+#
+# Call unfollowUser operation
+#
+##############################################################################
+call_unfollowUser() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=(followedUsername followerUsername)
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(    )
+    local path
+
+    if ! path=$(build_request_path "/users/{followedUsername}/followers/{followerUsername}" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="DELETE"
     local headers_curl
     headers_curl=$(header_arguments_to_curl)
     if [[ -n $header_accept ]]; then
@@ -1325,14 +1507,23 @@ case $key in
     deleteUser)
     operation="deleteUser"
     ;;
+    followUser)
+    operation="followUser"
+    ;;
     getUserByUsername)
     operation="getUserByUsername"
     ;;
     getUserComments)
     operation="getUserComments"
     ;;
+    getUserFollowers)
+    operation="getUserFollowers"
+    ;;
     listUsers)
     operation="listUsers"
+    ;;
+    unfollowUser)
+    operation="unfollowUser"
     ;;
     updateUser)
     operation="updateUser"
@@ -1429,14 +1620,23 @@ case $operation in
     deleteUser)
     call_deleteUser
     ;;
+    followUser)
+    call_followUser
+    ;;
     getUserByUsername)
     call_getUserByUsername
     ;;
     getUserComments)
     call_getUserComments
     ;;
+    getUserFollowers)
+    call_getUserFollowers
+    ;;
     listUsers)
     call_listUsers
+    ;;
+    unfollowUser)
+    call_unfollowUser
     ;;
     updateUser)
     call_updateUser
