add url shortener endpoints

diff --git a/socialapp/cli/socialapp-cli b/socialapp/cli/socialapp-cli
--- a/socialapp/cli/socialapp-cli
+++ b/socialapp/cli/socialapp-cli
@@ -123,6 +123,10 @@ operation_parameters_minimum_occurrences["listScopes:::limit"]=0
 operation_parameters_minimum_occurrences["listScopes:::offset"]=0
 operation_parameters_minimum_occurrences["updateScope:::id"]=1
 operation_parameters_minimum_occurrences["updateScope:::Scope"]=0
+operation_parameters_minimum_occurrences["createUrl:::URL"]=1
+operation_parameters_minimum_occurrences["deleteUrl:::alias"]=1
+operation_parameters_minimum_occurrences["getUrl:::alias"]=1
+operation_parameters_minimum_occurrences["getUrlData:::alias"]=1
 operation_parameters_minimum_occurrences["changePassword:::ChangePasswordRequest"]=1
 operation_parameters_minimum_occurrences["createUser:::CreateUserRequest"]=1
 operation_parameters_minimum_occurrences["deleteUser:::username"]=1
@@ -180,6 +184,10 @@ operation_parameters_maximum_occurrences["listScopes:::limit"]=0
 operation_parameters_maximum_occurrences["listScopes:::offset"]=0
 operation_parameters_maximum_occurrences["updateScope:::id"]=0
 operation_parameters_maximum_occurrences["updateScope:::Scope"]=0
+operation_parameters_maximum_occurrences["createUrl:::URL"]=0
+operation_parameters_maximum_occurrences["deleteUrl:::alias"]=0
+operation_parameters_maximum_occurrences["getUrl:::alias"]=0
+operation_parameters_maximum_occurrences["getUrlData:::alias"]=0
 operation_parameters_maximum_occurrences["changePassword:::ChangePasswordRequest"]=0
 operation_parameters_maximum_occurrences["createUser:::CreateUserRequest"]=0
 operation_parameters_maximum_occurrences["deleteUser:::username"]=0
@@ -234,6 +242,10 @@ operation_parameters_collection_type["listScopes:::limit"]=""
 operation_parameters_collection_type["listScopes:::offset"]=""
 operation_parameters_collection_type["updateScope:::id"]=""
 operation_parameters_collection_type["updateScope:::Scope"]=""
+operation_parameters_collection_type["createUrl:::URL"]=""
+operation_parameters_collection_type["deleteUrl:::alias"]=""
+operation_parameters_collection_type["getUrl:::alias"]=""
+operation_parameters_collection_type["getUrlData:::alias"]=""
 operation_parameters_collection_type["changePassword:::ChangePasswordRequest"]=""
 operation_parameters_collection_type["createUser:::CreateUserRequest"]=""
 operation_parameters_collection_type["deleteUser:::username"]=""
@@ -669,6 +681,9 @@ EOF
     echo -e "        * socialapp.users.roles.create - Create roles of a user"
     echo -e "        * socialapp.users.roles.update - Update roles of a user"
     echo -e "        * socialapp.users.roles.delete - Delete roles of a user"
+    echo -e "        * shortly.url.create - Create a url"
+    echo -e "        * shortly.url.update - Update a url"
+    echo -e "        * shortly.url.delete - Delete a url"
     echo ""
     echo -e "${BOLD}${WHITE}Operations (grouped by tags)${OFF}"
     echo ""
@@ -713,6 +728,15 @@ read -r -d '' ops <<EOF
   ${CYAN}getScope${OFF};Returns a scope (AUTH)
   ${CYAN}listScopes${OFF};Returns a list of scopes (AUTH)
   ${CYAN}updateScope${OFF};Update a scope (AUTH)
+EOF
+echo "  $ops" | column -t -s ';'
+    echo ""
+    echo -e "${BOLD}${WHITE}[uRL]${OFF}"
+read -r -d '' ops <<EOF
+  ${CYAN}createUrl${OFF}; (AUTH)
+  ${CYAN}deleteUrl${OFF}; (AUTH)
+  ${CYAN}getUrl${OFF}; (AUTH)
+  ${CYAN}getUrlData${OFF}; (AUTH)
 EOF
 echo "  $ops" | column -t -s ';'
     echo ""
@@ -1234,6 +1258,89 @@ print_updateScope_help() {
     echo -e "${result_color_table[${code:0:1}]}  401;Unauthorized${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
     code=0
     echo -e "${result_color_table[${code:0:1}]}  0;Unexpected error${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
+# Print help for createUrl operation
+#
+##############################################################################
+print_createUrl_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}createUrl - ${OFF}${BLUE}(AUTH - OAuth2)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "Returns a url" | paste -sd' ' | fold -sw 80
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}body${OFF} ${BLUE}[application/json]${OFF} ${RED}(required)${OFF}${OFF} - Create a new url" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=200
+    echo -e "${result_color_table[${code:0:1}]}  200;Url is returned${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=401
+    echo -e "${result_color_table[${code:0:1}]}  401;Unauthorized${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
+# Print help for deleteUrl operation
+#
+##############################################################################
+print_deleteUrl_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}deleteUrl - ${OFF}${BLUE}(AUTH - OAuth2)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "Delete a url" | paste -sd' ' | fold -sw 80
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}alias${OFF} ${BLUE}[string]${OFF} ${RED}(required)${OFF} ${CYAN}(default: null)${OFF} - The alias of the url ${YELLOW}Specify as: alias=value${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=204
+    echo -e "${result_color_table[${code:0:1}]}  204;Url was deleted successfully${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=404
+    echo -e "${result_color_table[${code:0:1}]}  404;Url not found${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
+# Print help for getUrl operation
+#
+##############################################################################
+print_getUrl_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}getUrl - ${OFF}${BLUE}(AUTH - OAuth2)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "Returns a url" | paste -sd' ' | fold -sw 80
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}alias${OFF} ${BLUE}[string]${OFF} ${RED}(required)${OFF} ${CYAN}(default: null)${OFF} - The alias of the url ${YELLOW}Specify as: alias=value${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=302
+    echo -e "${result_color_table[${code:0:1}]}  302;Redirect to the url${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+        echo -e "       ${BOLD}${WHITE}Response headers${OFF}"
+        echo -e "       ${BLUE}Location${OFF} - The url" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/        /'
+    code=404
+    echo -e "${result_color_table[${code:0:1}]}  404;Url not found${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
+# Print help for getUrlData operation
+#
+##############################################################################
+print_getUrlData_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}getUrlData - ${OFF}${BLUE}(AUTH - OAuth2)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "Returns a url" | paste -sd' ' | fold -sw 80
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}alias${OFF} ${BLUE}[string]${OFF} ${RED}(required)${OFF} ${CYAN}(default: null)${OFF} - The alias of the url ${YELLOW}Specify as: alias=value${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=200
+    echo -e "${result_color_table[${code:0:1}]}  200;Url is returned${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=404
+    echo -e "${result_color_table[${code:0:1}]}  404;Url not found${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
 }
 ##############################################################################
 #
@@ -2501,6 +2608,192 @@ call_updateScope() {
 
 ##############################################################################
 #
+# Call createUrl operation
+#
+##############################################################################
+call_createUrl() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=()
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(  )
+    local path
+
+    if ! path=$(build_request_path "/urls" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="POST"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    local body_json_curl=""
+
+    #
+    # Check if the user provided 'Content-type' headers in the
+    # command line. If not try to set them based on the OpenAPI specification
+    # if values produces and consumes are defined unambiguously
+    #
+    if [[ -z $header_content_type ]]; then
+        header_content_type="application/json"
+    fi
+
+
+    if [[ -z $header_content_type && "$force" = false ]]; then
+        :
+        echo "ERROR: Request's content-type not specified!!!"
+        echo "This operation expects content-type in one of the following formats:"
+        echo -e "\\t- application/json"
+        echo ""
+        echo "Use '--content-type' to set proper content type"
+        exit 1
+    else
+        headers_curl="${headers_curl} -H 'Content-type: ${header_content_type}'"
+    fi
+
+
+    #
+    # If we have received some body content over pipe, pass it from the
+    # temporary file to cURL
+    #
+    if [[ -n $body_content_temp_file ]]; then
+        if [[ "$print_curl" = true ]]; then
+            echo "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        else
+            eval "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        fi
+        rm "${body_content_temp_file}"
+    #
+    # If not, try to build the content body from arguments KEY==VALUE and KEY:=VALUE
+    #
+    else
+        body_json_curl=$(body_parameters_to_json)
+        if [[ "$print_curl" = true ]]; then
+            echo "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        else
+            eval "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        fi
+    fi
+}
+
+##############################################################################
+#
+# Call deleteUrl operation
+#
+##############################################################################
+call_deleteUrl() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=(alias)
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(  )
+    local path
+
+    if ! path=$(build_request_path "/urls/{alias}" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="DELETE"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    if [[ "$print_curl" = true ]]; then
+        echo "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    else
+        eval "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    fi
+}
+
+##############################################################################
+#
+# Call getUrl operation
+#
+##############################################################################
+call_getUrl() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=(alias)
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(  )
+    local path
+
+    if ! path=$(build_request_path "/urls/{alias}" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="GET"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    if [[ "$print_curl" = true ]]; then
+        echo "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    else
+        eval "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    fi
+}
+
+##############################################################################
+#
+# Call getUrlData operation
+#
+##############################################################################
+call_getUrlData() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=(alias)
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(  )
+    local path
+
+    if ! path=$(build_request_path "/urls/{alias}/data" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="GET"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    if [[ "$print_curl" = true ]]; then
+        echo "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    else
+        eval "curl -d '' ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\""
+    fi
+}
+
+##############################################################################
+#
 # Call changePassword operation
 #
 ##############################################################################
@@ -3367,6 +3660,18 @@ case $key in
     updateScope)
     operation="updateScope"
     ;;
+    createUrl)
+    operation="createUrl"
+    ;;
+    deleteUrl)
+    operation="deleteUrl"
+    ;;
+    getUrl)
+    operation="getUrl"
+    ;;
+    getUrlData)
+    operation="getUrlData"
+    ;;
     changePassword)
     operation="changePassword"
     ;;
@@ -3542,6 +3847,18 @@ case $operation in
     ;;
     updateScope)
     call_updateScope
+    ;;
+    createUrl)
+    call_createUrl
+    ;;
+    deleteUrl)
+    call_deleteUrl
+    ;;
+    getUrl)
+    call_getUrl
+    ;;
+    getUrlData)
+    call_getUrlData
     ;;
     changePassword)
     call_changePassword
