add scope to role

diff --git a/socialapp/cli/socialapp-cli b/socialapp/cli/socialapp-cli
--- a/socialapp/cli/socialapp-cli
+++ b/socialapp/cli/socialapp-cli
@@ -140,6 +140,8 @@ operation_parameters_minimum_occurrences["listUsers:::offset"]=0
 operation_parameters_minimum_occurrences["resetPassword:::ResetPasswordRequest"]=1
 operation_parameters_minimum_occurrences["unfollowUser:::followedUsername"]=1
 operation_parameters_minimum_occurrences["unfollowUser:::followerUsername"]=1
+operation_parameters_minimum_occurrences["updateRolesForUser:::username"]=1
+operation_parameters_minimum_occurrences["updateRolesForUser:::request_body"]=0
 operation_parameters_minimum_occurrences["updateUser:::username"]=1
 operation_parameters_minimum_occurrences["updateUser:::User"]=0
 
@@ -195,6 +197,8 @@ operation_parameters_maximum_occurrences["listUsers:::offset"]=0
 operation_parameters_maximum_occurrences["resetPassword:::ResetPasswordRequest"]=0
 operation_parameters_maximum_occurrences["unfollowUser:::followedUsername"]=0
 operation_parameters_maximum_occurrences["unfollowUser:::followerUsername"]=0
+operation_parameters_maximum_occurrences["updateRolesForUser:::username"]=0
+operation_parameters_maximum_occurrences["updateRolesForUser:::request_body"]=0
 operation_parameters_maximum_occurrences["updateUser:::username"]=0
 operation_parameters_maximum_occurrences["updateUser:::User"]=0
 
@@ -247,6 +251,8 @@ operation_parameters_collection_type["listUsers:::offset"]=""
 operation_parameters_collection_type["resetPassword:::ResetPasswordRequest"]=""
 operation_parameters_collection_type["unfollowUser:::followedUsername"]=""
 operation_parameters_collection_type["unfollowUser:::followerUsername"]=""
+operation_parameters_collection_type["updateRolesForUser:::username"]=""
+operation_parameters_collection_type["updateRolesForUser:::request_body"]=
 operation_parameters_collection_type["updateUser:::username"]=""
 operation_parameters_collection_type["updateUser:::User"]=""
 
@@ -661,6 +667,7 @@ EOF
     echo -e "        * socialapp.roles.scopes.delete - Delete scopes of a role"
     echo -e "        * socialapp.users.roles.list - List roles of a user"
     echo -e "        * socialapp.users.roles.create - Create roles of a user"
+    echo -e "        * socialapp.users.roles.update - Update roles of a user"
     echo -e "        * socialapp.users.roles.delete - Delete roles of a user"
     echo ""
     echo -e "${BOLD}${WHITE}Operations (grouped by tags)${OFF}"
@@ -723,6 +730,7 @@ read -r -d '' ops <<EOF
   ${CYAN}listUsers${OFF};List users (AUTH)
   ${CYAN}resetPassword${OFF};Reset password (AUTH)
   ${CYAN}unfollowUser${OFF};Remove a user as a follower (AUTH)
+  ${CYAN}updateRolesForUser${OFF};Update all roles for a user (AUTH)
   ${CYAN}updateUser${OFF};Update a user (AUTH)
 EOF
 echo "  $ops" | column -t -s ';'
@@ -1500,6 +1508,30 @@ print_unfollowUser_help() {
     echo -e "${BOLD}${WHITE}Responses${OFF}"
     code=200
     echo -e "${result_color_table[${code:0:1}]}  200;User was unfollowed successfully${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=401
+    echo -e "${result_color_table[${code:0:1}]}  401;Unauthorized${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=0
+    echo -e "${result_color_table[${code:0:1}]}  0;Unexpected error${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
+# Print help for updateRolesForUser operation
+#
+##############################################################################
+print_updateRolesForUser_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}updateRolesForUser - Update all roles for a user${OFF}${BLUE}(AUTH - OAuth2)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "Update all roles for a user" | paste -sd' ' | fold -sw 80
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}username${OFF} ${BLUE}[string]${OFF} ${RED}(required)${OFF} ${CYAN}(default: null)${OFF} - username of the user ${YELLOW}Specify as: username=value${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e "  * ${GREEN}body${OFF} ${BLUE}[application/json]${OFF}${OFF} - Update all roles for a user" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=200
+    echo -e "${result_color_table[${code:0:1}]}  200;Roles for a user${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
     code=401
     echo -e "${result_color_table[${code:0:1}]}  401;Unauthorized${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
     code=0
@@ -3027,6 +3059,84 @@ call_unfollowUser() {
 
 ##############################################################################
 #
+# Call updateRolesForUser operation
+#
+##############################################################################
+call_updateRolesForUser() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=(username)
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(  )
+    local path
+
+    if ! path=$(build_request_path "/users/{username}/roles" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="PUT"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    local body_json_curl=""
+
+    #
+    # Check if the user provided 'Content-type' headers in the
+    # command line. If not try to set them based on the OpenAPI specification
+    # if values produces and consumes are defined unambiguously
+    #
+    if [[ -z $header_content_type ]]; then
+        header_content_type="application/json"
+    fi
+
+
+    if [[ -z $header_content_type && "$force" = false ]]; then
+        :
+        echo "ERROR: Request's content-type not specified!!!"
+        echo "This operation expects content-type in one of the following formats:"
+        echo -e "\\t- application/json"
+        echo ""
+        echo "Use '--content-type' to set proper content type"
+        exit 1
+    else
+        headers_curl="${headers_curl} -H 'Content-type: ${header_content_type}'"
+    fi
+
+
+    #
+    # If we have received some body content over pipe, pass it from the
+    # temporary file to cURL
+    #
+    if [[ -n $body_content_temp_file ]]; then
+        if [[ "$print_curl" = true ]]; then
+            echo "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        else
+            eval "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        fi
+        rm "${body_content_temp_file}"
+    #
+    # If not, try to build the content body from arguments KEY==VALUE and KEY:=VALUE
+    #
+    else
+        body_json_curl=$(body_parameters_to_json)
+        if [[ "$print_curl" = true ]]; then
+            echo "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        else
+            eval "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        fi
+    fi
+}
+
+##############################################################################
+#
 # Call updateUser operation
 #
 ##############################################################################
@@ -3293,6 +3403,9 @@ case $key in
     unfollowUser)
     operation="unfollowUser"
     ;;
+    updateRolesForUser)
+    operation="updateRolesForUser"
+    ;;
     updateUser)
     operation="updateUser"
     ;;
@@ -3465,6 +3578,9 @@ case $operation in
     ;;
     unfollowUser)
     call_unfollowUser
+    ;;
+    updateRolesForUser)
+    call_updateRolesForUser
     ;;
     updateUser)
     call_updateUser
